version: '3.1'
 
services:
 api_measureGroups:
    image: autotests_measureGroups
    build:
      context: .
      args:
        APP_ENV_TESTAPIURL: testsApiUrl,
        APP_ENV_TESTAPIURLAUTHENTICATEPATH: testsApiUrlAuthenticatePath
      dockerfile: DockerFile_measureGroups
    environment:
      - TEAMCITY_PROJECT_NAME