version: '3.1'
 
services:
 api__dimensions:
    image: autotests__dimensions
    build:
      context: .
      dockerfile: DockerFile_dimensions
    environment:
      - TEAMCITY_PROJECT_NAME
      - ApiUrl=${ApiUrl}
      - ApiUrlAuthenticatePath=${ApiUrlAuthenticatePath}