version: '3.1'
 
services:
 api_measureGroups1:
    image: autotests_measureGroups1
    build:
      context: .
      dockerfile: DockerFile_measureGroups
    environment:
      - TEAMCITY_PROJECT_NAME