version: '3.1'
 
services:
 api_measureGroups:
    image: autotests_measureGroups
    build:
      context: .
      dockerfile: DockerFile_measureGroups
    environment:
      - TEAMCITY_PROJECT_NAME
      - ApiUrl=${ApiUrl}
      - ApiUrlAuthenticatePath=${ApiUrlAuthenticatePath}